//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dokumentooborot7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Документ сох.
    /// </summary>
    // *** Start programmer edit section *** (ДокументСох CustomAttributes)

    // *** End programmer edit section *** (ДокументСох CustomAttributes)
    [AutoAltered()]
    [Caption("Документ сох")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокументСохE", new string[] {
            "ДатаСохранения as \'Дата сохранения\'"})]
    [AssociatedDetailViewAttribute("ДокументСохE", "ТЧУтвержДок", "ТЧУтвержДокE", true, "", "Т ч утверж док", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("ДокументСохE", "ТЧСоздДок", "ТЧСоздДокE", true, "", "Т ч созд док", true, new string[] {
            ""})]
    [View("ДокументСохL", new string[] {
            "ДатаСохранения as \'Дата сохранения\'"})]
    public class ДокументСох : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаСохранения = System.DateTime.Now;
        
        private IIS.Dokumentooborot7.DetailArrayOfТЧСоздДок fТЧСоздДок;
        
        private IIS.Dokumentooborot7.DetailArrayOfТЧУтвержДок fТЧУтвержДок;
        
        // *** Start programmer edit section *** (ДокументСох CustomMembers)

        // *** End programmer edit section *** (ДокументСох CustomMembers)

        
        /// <summary>
        /// ДатаСохранения.
        /// </summary>
        // *** Start programmer edit section *** (ДокументСох.ДатаСохранения CustomAttributes)

        // *** End programmer edit section *** (ДокументСох.ДатаСохранения CustomAttributes)
        public virtual System.DateTime ДатаСохранения
        {
            get
            {
                // *** Start programmer edit section *** (ДокументСох.ДатаСохранения Get start)

                // *** End programmer edit section *** (ДокументСох.ДатаСохранения Get start)
                System.DateTime result = this.fДатаСохранения;
                // *** Start programmer edit section *** (ДокументСох.ДатаСохранения Get end)

                // *** End programmer edit section *** (ДокументСох.ДатаСохранения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокументСох.ДатаСохранения Set start)

                // *** End programmer edit section *** (ДокументСох.ДатаСохранения Set start)
                this.fДатаСохранения = value;
                // *** Start programmer edit section *** (ДокументСох.ДатаСохранения Set end)

                // *** End programmer edit section *** (ДокументСох.ДатаСохранения Set end)
            }
        }
        
        /// <summary>
        /// Документ сох.
        /// </summary>
        // *** Start programmer edit section *** (ДокументСох.ТЧСоздДок CustomAttributes)

        // *** End programmer edit section *** (ДокументСох.ТЧСоздДок CustomAttributes)
        public virtual IIS.Dokumentooborot7.DetailArrayOfТЧСоздДок ТЧСоздДок
        {
            get
            {
                // *** Start programmer edit section *** (ДокументСох.ТЧСоздДок Get start)

                // *** End programmer edit section *** (ДокументСох.ТЧСоздДок Get start)
                if ((this.fТЧСоздДок == null))
                {
                    this.fТЧСоздДок = new IIS.Dokumentooborot7.DetailArrayOfТЧСоздДок(this);
                }
                IIS.Dokumentooborot7.DetailArrayOfТЧСоздДок result = this.fТЧСоздДок;
                // *** Start programmer edit section *** (ДокументСох.ТЧСоздДок Get end)

                // *** End programmer edit section *** (ДокументСох.ТЧСоздДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокументСох.ТЧСоздДок Set start)

                // *** End programmer edit section *** (ДокументСох.ТЧСоздДок Set start)
                this.fТЧСоздДок = value;
                // *** Start programmer edit section *** (ДокументСох.ТЧСоздДок Set end)

                // *** End programmer edit section *** (ДокументСох.ТЧСоздДок Set end)
            }
        }
        
        /// <summary>
        /// Документ сох.
        /// </summary>
        // *** Start programmer edit section *** (ДокументСох.ТЧУтвержДок CustomAttributes)

        // *** End programmer edit section *** (ДокументСох.ТЧУтвержДок CustomAttributes)
        public virtual IIS.Dokumentooborot7.DetailArrayOfТЧУтвержДок ТЧУтвержДок
        {
            get
            {
                // *** Start programmer edit section *** (ДокументСох.ТЧУтвержДок Get start)

                // *** End programmer edit section *** (ДокументСох.ТЧУтвержДок Get start)
                if ((this.fТЧУтвержДок == null))
                {
                    this.fТЧУтвержДок = new IIS.Dokumentooborot7.DetailArrayOfТЧУтвержДок(this);
                }
                IIS.Dokumentooborot7.DetailArrayOfТЧУтвержДок result = this.fТЧУтвержДок;
                // *** Start programmer edit section *** (ДокументСох.ТЧУтвержДок Get end)

                // *** End programmer edit section *** (ДокументСох.ТЧУтвержДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокументСох.ТЧУтвержДок Set start)

                // *** End programmer edit section *** (ДокументСох.ТЧУтвержДок Set start)
                this.fТЧУтвержДок = value;
                // *** Start programmer edit section *** (ДокументСох.ТЧУтвержДок Set end)

                // *** End programmer edit section *** (ДокументСох.ТЧУтвержДок Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокументСохE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокументСохE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокументСохE", typeof(IIS.Dokumentooborot7.ДокументСох));
                }
            }
            
            /// <summary>
            /// "ДокументСохL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокументСохL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокументСохL", typeof(IIS.Dokumentooborot7.ДокументСох));
                }
            }
        }
    }
}
