//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dokumentooborot7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч созд док.
    /// </summary>
    // *** Start programmer edit section *** (ТЧСоздДок CustomAttributes)

    // *** End programmer edit section *** (ТЧСоздДок CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч созд док")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧСоздДокE", new string[] {
            "ФормаДокумента as \'Форма документа\'",
            "ФормаДокумента.Дата",
            "ФормаДокумента.Наименование as \'Наименование\'",
            "ФормаДокумента.АвПользователи.Сотрудники.ФИОСотрудника"}, Hidden=new string[] {
            "ФормаДокумента.Наименование"})]
    [MasterViewDefineAttribute("ТЧСоздДокE", "ФормаДокумента", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class ТЧСоздДок : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Dokumentooborot7.ФормаДокумента fФормаДокумента;
        
        private IIS.Dokumentooborot7.ДокументСох fДокументСох;
        
        // *** Start programmer edit section *** (ТЧСоздДок CustomMembers)

        // *** End programmer edit section *** (ТЧСоздДок CustomMembers)

        
        /// <summary>
        /// Т ч созд док.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСоздДок.ФормаДокумента CustomAttributes)

        // *** End programmer edit section *** (ТЧСоздДок.ФормаДокумента CustomAttributes)
        [PropertyStorage(new string[] {
                "ФормаДокумента"})]
        [NotNull()]
        public virtual IIS.Dokumentooborot7.ФормаДокумента ФормаДокумента
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСоздДок.ФормаДокумента Get start)

                // *** End programmer edit section *** (ТЧСоздДок.ФормаДокумента Get start)
                IIS.Dokumentooborot7.ФормаДокумента result = this.fФормаДокумента;
                // *** Start programmer edit section *** (ТЧСоздДок.ФормаДокумента Get end)

                // *** End programmer edit section *** (ТЧСоздДок.ФормаДокумента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСоздДок.ФормаДокумента Set start)

                // *** End programmer edit section *** (ТЧСоздДок.ФормаДокумента Set start)
                this.fФормаДокумента = value;
                // *** Start programmer edit section *** (ТЧСоздДок.ФормаДокумента Set end)

                // *** End programmer edit section *** (ТЧСоздДок.ФормаДокумента Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Dokumentooborot7.ДокументСох.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСоздДок.ДокументСох CustomAttributes)

        // *** End programmer edit section *** (ТЧСоздДок.ДокументСох CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ДокументСох"})]
        public virtual IIS.Dokumentooborot7.ДокументСох ДокументСох
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСоздДок.ДокументСох Get start)

                // *** End programmer edit section *** (ТЧСоздДок.ДокументСох Get start)
                IIS.Dokumentooborot7.ДокументСох result = this.fДокументСох;
                // *** Start programmer edit section *** (ТЧСоздДок.ДокументСох Get end)

                // *** End programmer edit section *** (ТЧСоздДок.ДокументСох Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСоздДок.ДокументСох Set start)

                // *** End programmer edit section *** (ТЧСоздДок.ДокументСох Set start)
                this.fДокументСох = value;
                // *** Start programmer edit section *** (ТЧСоздДок.ДокументСох Set end)

                // *** End programmer edit section *** (ТЧСоздДок.ДокументСох Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧСоздДокE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧСоздДокE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧСоздДокE", typeof(IIS.Dokumentooborot7.ТЧСоздДок));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧСоздДок.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧСоздДок CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧСоздДок CustomAttributes)
    public class DetailArrayOfТЧСоздДок : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Dokumentooborot7.DetailArrayOfТЧСоздДок members)

        // *** End programmer edit section *** (IIS.Dokumentooborot7.DetailArrayOfТЧСоздДок members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧСоздДок by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧСоздДок.
        /// </summary>
        public DetailArrayOfТЧСоздДок(IIS.Dokumentooborot7.ДокументСох fДокументСох) : 
                base(typeof(ТЧСоздДок), ((ICSSoft.STORMNET.DataObject)(fДокументСох)))
        {
        }
        
        public IIS.Dokumentooborot7.ТЧСоздДок this[int index]
        {
            get
            {
                return ((IIS.Dokumentooborot7.ТЧСоздДок)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Dokumentooborot7.ТЧСоздДок dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
