//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dokumentooborot7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Утверждение док.
    /// </summary>
    // *** Start programmer edit section *** (УтверждениеДок CustomAttributes)

    // *** End programmer edit section *** (УтверждениеДок CustomAttributes)
    [AutoAltered()]
    [Caption("Утверждение док")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УтверждениеДокE", new string[] {
            "Дата as \'Дата\'",
            "Утверждение as \'Утверждение\'",
            "ФормаДокумента as \'Форма документа\'",
            "ФормаДокумента.Наименование as \'Наименование\'",
            "АвПользователи as \'Ав пользователи\'",
            "АвПользователи.Логин as \'Логин\'"}, Hidden=new string[] {
            "ФормаДокумента.Наименование",
            "АвПользователи.Логин"})]
    [MasterViewDefineAttribute("УтверждениеДокE", "ФормаДокумента", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("УтверждениеДокE", "АвПользователи", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Логин")]
    [View("УтверждениеДокL", new string[] {
            "Дата as \'Дата\'",
            "Утверждение as \'Утверждение\'",
            "ФормаДокумента.Наименование as \'Наименование\'",
            "АвПользователи.Сотрудники.ФИОСотрудника"})]
    public class УтверждениеДок : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private IIS.Dokumentooborot7.Утверждение fУтверждение;
        
        private IIS.Dokumentooborot7.ФормаДокумента fФормаДокумента;
        
        private IIS.Dokumentooborot7.АвПользователи fАвПользователи;
        
        // *** Start programmer edit section *** (УтверждениеДок CustomMembers)

        // *** End programmer edit section *** (УтверждениеДок CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (УтверждениеДок.Дата CustomAttributes)

        // *** End programmer edit section *** (УтверждениеДок.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (УтверждениеДок.Дата Get start)

                // *** End programmer edit section *** (УтверждениеДок.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (УтверждениеДок.Дата Get end)

                // *** End programmer edit section *** (УтверждениеДок.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УтверждениеДок.Дата Set start)

                // *** End programmer edit section *** (УтверждениеДок.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (УтверждениеДок.Дата Set end)

                // *** End programmer edit section *** (УтверждениеДок.Дата Set end)
            }
        }
        
        /// <summary>
        /// Утверждение.
        /// </summary>
        // *** Start programmer edit section *** (УтверждениеДок.Утверждение CustomAttributes)

        // *** End programmer edit section *** (УтверждениеДок.Утверждение CustomAttributes)
        public virtual IIS.Dokumentooborot7.Утверждение Утверждение
        {
            get
            {
                // *** Start programmer edit section *** (УтверждениеДок.Утверждение Get start)

                // *** End programmer edit section *** (УтверждениеДок.Утверждение Get start)
                IIS.Dokumentooborot7.Утверждение result = this.fУтверждение;
                // *** Start programmer edit section *** (УтверждениеДок.Утверждение Get end)

                // *** End programmer edit section *** (УтверждениеДок.Утверждение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УтверждениеДок.Утверждение Set start)

                // *** End programmer edit section *** (УтверждениеДок.Утверждение Set start)
                this.fУтверждение = value;
                // *** Start programmer edit section *** (УтверждениеДок.Утверждение Set end)

                // *** End programmer edit section *** (УтверждениеДок.Утверждение Set end)
            }
        }
        
        /// <summary>
        /// Утверждение док.
        /// </summary>
        // *** Start programmer edit section *** (УтверждениеДок.АвПользователи CustomAttributes)

        // *** End programmer edit section *** (УтверждениеДок.АвПользователи CustomAttributes)
        [PropertyStorage(new string[] {
                "АвПользователи"})]
        [NotNull()]
        public virtual IIS.Dokumentooborot7.АвПользователи АвПользователи
        {
            get
            {
                // *** Start programmer edit section *** (УтверждениеДок.АвПользователи Get start)

                // *** End programmer edit section *** (УтверждениеДок.АвПользователи Get start)
                IIS.Dokumentooborot7.АвПользователи result = this.fАвПользователи;
                // *** Start programmer edit section *** (УтверждениеДок.АвПользователи Get end)

                // *** End programmer edit section *** (УтверждениеДок.АвПользователи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УтверждениеДок.АвПользователи Set start)

                // *** End programmer edit section *** (УтверждениеДок.АвПользователи Set start)
                this.fАвПользователи = value;
                // *** Start programmer edit section *** (УтверждениеДок.АвПользователи Set end)

                // *** End programmer edit section *** (УтверждениеДок.АвПользователи Set end)
            }
        }
        
        /// <summary>
        /// Утверждение док.
        /// </summary>
        // *** Start programmer edit section *** (УтверждениеДок.ФормаДокумента CustomAttributes)

        // *** End programmer edit section *** (УтверждениеДок.ФормаДокумента CustomAttributes)
        [PropertyStorage(new string[] {
                "ФормаДокумента"})]
        [NotNull()]
        public virtual IIS.Dokumentooborot7.ФормаДокумента ФормаДокумента
        {
            get
            {
                // *** Start programmer edit section *** (УтверждениеДок.ФормаДокумента Get start)

                // *** End programmer edit section *** (УтверждениеДок.ФормаДокумента Get start)
                IIS.Dokumentooborot7.ФормаДокумента result = this.fФормаДокумента;
                // *** Start programmer edit section *** (УтверждениеДок.ФормаДокумента Get end)

                // *** End programmer edit section *** (УтверждениеДок.ФормаДокумента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УтверждениеДок.ФормаДокумента Set start)

                // *** End programmer edit section *** (УтверждениеДок.ФормаДокумента Set start)
                this.fФормаДокумента = value;
                // *** Start programmer edit section *** (УтверждениеДок.ФормаДокумента Set end)

                // *** End programmer edit section *** (УтверждениеДок.ФормаДокумента Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УтверждениеДокE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УтверждениеДокE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УтверждениеДокE", typeof(IIS.Dokumentooborot7.УтверждениеДок));
                }
            }
            
            /// <summary>
            /// "УтверждениеДокL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УтверждениеДокL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УтверждениеДокL", typeof(IIS.Dokumentooborot7.УтверждениеДок));
                }
            }
        }
    }
}
