import IISDokumentooborot7ФормаДокументаEController from '../i-i-s-dokumentooborot7-форма-документа-e';

var IISDokumentooborot7ФормаДокументаENewController = IISDokumentooborot7ФормаДокументаEController;
export default IISDokumentooborot7ФормаДокументаENewController;
